spring:
  application:
    name: devtools-example
  cloud:
    apisix:
      discovery:
        address: http://nuc8i7.wcj.plus:9080
        control-address: http://nuc8i7.wcj.plus:9092
        active-health-check: true
        passive-health-check: true
        active-health-check-path: /hello
        token: edd1c9f034335f136f87ad84b625c8f1
      devtools:
        gateway-address: http://nuc8i7.wcj.plus:9080
        ports:
          - 28080
          - 38080
          - 48080
server:
  port: 8080
